"""twinworld — counterfactual reasoning over symbolic state-transition traces."""

from .api import (
    DEFAULT_ABSTRACTIONS,
    Backtracking,
    CausalRepresentation,
    ConfidenceReport,
    Contrastive,
    CounterfactualItem,
    CounterfactualSet,
    IdentificationError,
    IdentifiedQuery,
    Interventional,
    PertinentNegative,
    Representational,
    assess,
    compute,
    identify,
    model,
    predict,
    refute,
)
from .alternatives import GENERIC_POLICIES, Alternatives, rank_preimages
from .analogy import content_vector, induce_rules, retrieve, structure_map
from .backend import (
    REPRESENTATIONS,
    Addition,
    ConformanceReport,
    capabilities,
    conformance_battery,
    get_representation,
    register,
    representation_of,
)
from .concepts import DEFAULT_CONCEPTS, ConceptNet, learn_concepts
from .engine import Counterfactual, Solution, Task, Trace, UnsolvedTaskError, solve
from .mechanisms import (
    All,
    ByAttr,
    ByColour,
    Delete,
    Identity,
    Largest,
    Mechanism,
    Not,
    ObjectRule,
    Recolor,
    RecolourTo,
    Smallest,
    Translate,
    TranslateBy,
    candidate_primitives,
)
from .metrics import (
    MetricVector,
    diversity,
    dominates,
    edited_steps,
    evaluate,
    pareto_front,
    proximity,
    responsibility_profile,
    sparsity,
    validity,
)
from .refute import RefutationReport
from .select import POLICIES, resolve_with_probe, select
from .representation import Grid, Obj, StateGraph, as_grid, match_objects, parse_grid

__version__ = "0.1.0"

__all__ = [
    "Addition",
    "All",
    "Alternatives",
    "Backtracking",
    "ByAttr",
    "ByColour",
    "CausalRepresentation",
    "ConfidenceReport",
    "ConformanceReport",
    "Contrastive",
    "ConceptNet",
    "Counterfactual",
    "CounterfactualItem",
    "CounterfactualSet",
    "DEFAULT_ABSTRACTIONS",
    "DEFAULT_CONCEPTS",
    "GENERIC_POLICIES",
    "POLICIES",
    "REPRESENTATIONS",
    "Delete",
    "Grid",
    "Largest",
    "Not",
    "ObjectRule",
    "PertinentNegative",
    "RecolourTo",
    "Representational",
    "Smallest",
    "TranslateBy",
    "content_vector",
    "induce_rules",
    "retrieve",
    "structure_map",
    "IdentificationError",
    "IdentifiedQuery",
    "Identity",
    "Interventional",
    "Mechanism",
    "MetricVector",
    "Obj",
    "Recolor",
    "RefutationReport",
    "Solution",
    "StateGraph",
    "Task",
    "Trace",
    "Translate",
    "UnsolvedTaskError",
    "as_grid",
    "assess",
    "candidate_primitives",
    "capabilities",
    "compute",
    "conformance_battery",
    "diversity",
    "dominates",
    "edited_steps",
    "evaluate",
    "get_representation",
    "identify",
    "learn_concepts",
    "match_objects",
    "model",
    "pareto_front",
    "parse_grid",
    "predict",
    "proximity",
    "rank_preimages",
    "refute",
    "register",
    "representation_of",
    "resolve_with_probe",
    "responsibility_profile",
    "select",
    "solve",
    "sparsity",
    "validity",
]
