"""Causal validation: CausalARC provenance + L1/L2/L3 agreement harness.

Part 1 loads real CausalARC tasks and honestly reports what the symbolic
vocabulary can do with them (their SCMs change grid dimensions, which is
outside the current mechanism language — the number to improve on later).

Part 2 measures Pearl-ladder agreement on in-house latent-SCM tasks where
ground truth is exact by construction:
  L1 (association)     — induced program reproduces the held-out test output;
  L2 (intervention)    — do(last step = alternative): engine outcome vs the
                          edited latent program's outcome;
  L3 (counterfactual)  — backtracking to a fresh input world under fixed laws
                          vs the latent program on that input.
Agreement is reported overall AND split by whether induction recovered the
latent program syntactically — observational equivalence need not survive
interventions, which is the underdetermination story at ladder level 2.

Usage: python examples/causal_validation.py [N_INSTANCES]
"""

import random
import sys

import twinworld
from twinworld import UnsolvedTaskError
from twinworld.benchmark import random_grid, random_task
from twinworld.engine import ApplyCache, backtrack, intervene

N = int(sys.argv[1]) if len(sys.argv) > 1 else 30

# ---------------------------------------------------------------- part 1
print("Part 1 — CausalARC (Maasch et al. 2025, HF: jmaasch/causal_arc)")
try:
    from twinworld.domains.causalarc import load_causalarc

    causal_tasks = load_causalarc("counting")
    fitted = 0
    for ct in causal_tasks:
        try:
            twinworld.model(ct.task)
            fitted += 1
        except UnsolvedTaskError:
            pass
    print(f"  loaded {len(causal_tasks)} counting tasks "
          f"({sum(len(d) for ct in causal_tasks for d in ct.cf_demos)} labelled "
          f"counterfactual pairs); symbolic vocabulary fits {fitted}/{len(causal_tasks)} "
          f"(their SCMs change grid dimensions — outside the current language)")
except Exception as err:  # network-optional: the harness below is self-sufficient
    print(f"  dataset unavailable ({err}); continuing with in-house ground truth")

# ---------------------------------------------------------------- part 2
print(f"\nPart 2 — L1/L2/L3 agreement on {N} in-house latent-SCM instances")
rng = random.Random(1)
made = 0
l1 = {"total": 0, "ok": 0}
l2 = {"total": 0, "ok": 0, "recovered_ok": 0, "recovered_total": 0}
l3 = {"total": 0, "ok": 0}
attempts = 0
while made < N and attempts < N * 30:
    attempts += 1
    instance = random_task(rng)
    if instance is None:
        continue
    task, latent = instance
    made += 1
    try:
        rep = twinworld.model(task)
    except UnsolvedTaskError:
        continue
    sol = rep.solution
    cache = ApplyCache()
    recovered = tuple(sol.program) == tuple(latent)

    # L1: association — held-out test output (generated by the latent)
    l1["total"] += 1
    expected = twinworld.as_grid(task.test[0][1])
    if sol.test_traces and sol.test_traces[0].outcome.key == expected:
        l1["ok"] += 1

    # L2: intervention — do(last step = alternative), engine vs edited latent
    trace = sol.train_traces[0]
    step = len(sol.program) - 1
    for alt in twinworld.candidate_primitives(task.colours(), background=0):
        if alt == latent[-1] or alt == sol.program[step]:
            continue
        truth = cache.run(trace.states[0], tuple(latent[:-1]) + (alt,))
        if truth is None:
            continue
        cf = intervene(sol, trace, step, alt)
        l2["total"] += 1
        agree = cf.applicable and cf.counterfactual.outcome == truth.outcome
        l2["ok"] += agree
        if recovered:
            l2["recovered_total"] += 1
            l2["recovered_ok"] += agree
        break

    # L3: counterfactual — a fresh input world under fixed laws
    fresh = random_grid(rng)
    if fresh is None:
        continue
    truth = cache.run(twinworld.parse_grid(fresh), tuple(latent))
    if truth is None:
        continue
    cf = backtrack(sol, trace, fresh)
    l3["total"] += 1
    l3["ok"] += cf.applicable and cf.counterfactual.outcome == truth.outcome

print(f"  L1 association   : {l1['ok']}/{l1['total']}")
print(f"  L2 intervention  : {l2['ok']}/{l2['total']} "
      f"(when latent recovered syntactically: "
      f"{l2['recovered_ok']}/{l2['recovered_total']})")
print(f"  L3 counterfactual: {l3['ok']}/{l3['total']}")
print("  disagreements are observational equivalence failing to survive the "
      "ladder — underdetermination at L2/L3, not engine error")